name: Publish Launch Darkly Utils Library - @common-ts-libs/launch-darkly-utils
run-name: Publish Launch Darkly Utils Library
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'backend/launch-darkly-utils/**'

jobs:
  publish_lib:
    strategy:
      fail-fast: false
      matrix:
        accounts: [ { account: dev, id: 980692338090 } ]

    uses: qriomatrix/qriomatrix-reusable-github-workflows/.github/workflows/npm-publish-lib-template.yml@v1.0.0
    with:
      AWS_ACCOUNT_ID: ${{ matrix.accounts.id }}
      REPOSITORY: 'common-ts-libs'
      WORKING_DIRECTORY: 'backend/launch-darkly-utils'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.CDK_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CDK_AWS_SECRET_ACCESS_KEY }}